const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=new Date().toISOString().slice(0,10),screens=['home','game','result'];
const seasonNo=Math.max(1,Math.floor((Date.now()-Date.UTC(2026,7,1))/(30*86400000))+1);
let daily=[],timer=null,confidence=1,state={round:0,correct:0,score:0,marks:[],mode:'daily',start:0,cats:{}};

const fallback=[
{type:'LOGIC DUEL',category:'Logic',q:'A farmer has 17 sheep. All but 9 run away. How many remain?',sub:'The obvious arithmetic answer is a trap.',options:['8','9','17','26'],answer:1,why:'“All but 9” means 9 stayed.',aiTake:'I over-weighted subtraction instead of parsing the phrase.'},
{type:'PATTERN HACK',category:'Patterns',q:'What comes next: 1, 11, 21, 1211, 111221, ?',sub:'Read the previous number aloud.',options:['312211','122211','1113213211','311221'],answer:0,why:'111221 is three 1s, two 2s, one 1 → 312211.',aiTake:'The sequence describes the previous term rather than doing arithmetic.'},
{type:'TRUTH TEST',category:'Reasoning',q:'Which statement is definitely true?',sub:'No browsing. Just reasoning.',options:['Every prime is odd.','Some even numbers are prime.','Every square is even.','Negative numbers cannot be squared.'],answer:1,why:'2 is both even and prime.',aiTake:'The universal claims collapse under simple counterexamples.'},
{type:'AI LANGUAGE TRAP',category:'Language',q:'Which phrase is the stronger clue text may be AI-written?',sub:'Neither proves anything alone.',options:['I dunno, it felt weird.','In today’s rapidly evolving landscape…','Honestly, I missed the bus.','My dog ate the corner of it.'],answer:1,why:'That polished generic transition is common in generated prose.',aiTake:'Generic framing can sound polished while carrying little detail.'},
{type:'HUMAN OR AI',category:'Language',q:'Which line sounds more AI-generated?',sub:'Pick the more generic polished sentence.',options:['I forgot my umbrella again. Classic me.','The rainfall created a profoundly atmospheric experience that enhanced my emotional connection to the environment.','My socks are soaked.','I ran back for the umbrella and missed the train.'],answer:1,why:'The abstract, over-polished language is the stronger clue.',aiTake:'The sentence stacks abstractions instead of concrete detail.'}
];
const impossible={type:'IMPOSSIBLE',category:'Logic',q:'Three switches are downstairs. One controls a bulb upstairs. You may go upstairs only once. How do you identify the correct switch?',sub:'Think beyond whether the bulb is simply on or off.',options:['Flip one and go upstairs','Turn one on, wait, turn it off, turn another on, then go upstairs','Turn all three on','There is no way'],answer:1,why:'The lit bulb is switch two; a warm unlit bulb is switch one; cold and unlit is switch three.',aiTake:'Heat becomes a second information channel.'};
const personas=[{name:'Byte',face:'🤖',taunts:['Humans usually miss this one.','Try not to embarrass your species.'],win:['...Lucky.','Statistically irritating.'],lose:['That one was obvious.','Machine: 1. Ego: 0.']},{name:'Sphinx',face:'🗿',taunts:['Answer carefully, mortal.','Confidence is charming.'],win:['You may pass. For now.'],lose:['Predictable.']},{name:'Glitch',face:'👾',taunts:['beep boop skill issue','Speedrun your regret.'],win:['okay that was clean 😒'],lose:['L + ratio + artificial intelligence']}];
const achievementDefs=[['first','First Blood','Win your first question','⚔️'],['perfect','Machine Humbled','Score 5/5','🏆'],['streak7','Habit Formed','Reach a 7-day streak','🔥'],['rating1200','Big Brain','Reach 1200 Arena rating','🧠'],['plays25','Regular Human','Complete 25 battles','🎮'],['logic10','Logic Hunter','Get 10 logic questions right','🕵️'],['boss','Boss Breaker','Defeat a weekly boss','👹'],['impossible','One Percenter','Solve the Impossible Question','☠️']];

function profile(){return JSON.parse(localStorage.getItem('beatAIProfile')||'{"streak":0,"best":0,"last":"","rating":1000,"xp":0,"plays":0,"wins":0,"unlocked":[],"cats":{},"rewards":[]}')}
function saveProfile(p){localStorage.setItem('beatAIProfile',JSON.stringify(p))}
function billing(){return JSON.parse(localStorage.getItem('beatAIBilling')||'{"tier":"free"}')}
function setBilling(b){localStorage.setItem('beatAIBilling',JSON.stringify(b));refreshBilling()}
function persona(){return personas[(new Date().getUTCDate()+seasonNo)%personas.length]}
function rand(a){return a[Math.floor(Math.random()*a.length)]}
function titleFor(xp){return xp>=5000?'Human Legend':xp>=3000?'Machine Whisperer':xp>=1800?'AI Slayer':xp>=1000?'Logic Hunter':xp>=500?'Investigator':xp>=200?'Critical Thinker':'Novice Human'}
function levelFor(xp){return Math.floor(xp/250)+1}
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));scrollTo(0,0)}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}

function refresh(){const p=profile(),pe=persona();const r=p.best?Math.max(1,8400-Math.floor(((p.rating||1000)-900)*4.4)-(p.streak||0)*21):'—';$('#streak').textContent=`${p.streak||0} 🔥`;$('#best').textContent=p.best?`${p.best}/5`:'—';$('#rating').textContent=p.rating||1000;$('#ratingTop').textContent=p.rating||1000;$('#rank').textContent=r==='—'?'#—':`#${r.toLocaleString()}`;$('#titleBadge').textContent=titleFor(p.xp||0).toUpperCase();$('#seasonText').textContent=`Season ${seasonNo} • Level ${levelFor(p.xp||0)}`;$('#personaHome').textContent=`${pe.face} ${pe.name} — “${pe.taunts[1]||pe.taunts[0]}”`;renderFeed();refreshBilling()}
function refreshBilling(){const b=billing(),pro=b.tier==='pro';$$('[data-promode]').forEach(x=>x.classList.toggle('locked',!pro));$('#proBtn').textContent=pro?'✦ PRO ✓':'✦ PRO';$('#proTitle').textContent=pro?'Beat AI Pro Active':'Join Beat AI Pro';$('#proCopy').textContent=pro?'Your Human Resistance membership is active on this device.':'Unlimited battles, Lightning, Boss Battles, no ads, advanced stats and exclusive cosmetics.';$('#upgradeBtn').hidden=pro;$('#restoreBtn').hidden=pro;$('#manageBtn').hidden=!(pro&&b.customerId)}

async function loadDaily(){try{const r=await fetch('/api/daily');const d=await r.json();daily=Array.isArray(d.challenges)&&d.challenges.length===5?d.challenges.map((x,i)=>({...x,category:x.category||fallback[i].category,aiTake:x.aiTake||x.why})):fallback;$('#status').textContent=d.source==='generated'?'Fresh AI challenge ready.':'Today’s challenge ready.'}catch{daily=fallback;$('#status').textContent='Challenge ready — fallback mode.'}}
function requirePro(action){if(billing().tier==='pro')return action();toast('That mode is a Beat AI Pro perk ✦');$('#proCard').scrollIntoView({behavior:'smooth',block:'center'})}
function start(mode='daily'){clearInterval(timer);if(['practice','lightning','boss'].includes(mode)&&billing().tier!=='pro')return requirePro(()=>start(mode));state={round:0,correct:0,score:0,marks:[],mode,start:Date.now(),cats:{}};confidence=1;if(mode==='practice')daily=[...fallback].sort(()=>Math.random()-.5);if(mode==='boss')daily=[...fallback,...fallback].sort(()=>Math.random()-.5);if(mode==='impossible')daily=[impossible];show('game');render()}
function totalRounds(){return state.mode==='boss'?10:state.mode==='impossible'?1:5}
function render(){clearInterval(timer);const total=totalRounds(),c=daily[state.round]||fallback[state.round%fallback.length],pe=persona();$('#round').textContent=`${state.round+1} / ${total}`;$('#bar').style.width=`${((state.round+1)/total)*100}%`;$('#points').textContent=`${Math.max(0,Math.round(state.score))} pts`;$('#type').textContent=`${c.type} · ${c.category||'Reasoning'}`;$('#q').textContent=c.q;$('#sub').textContent=c.sub||'';$('#feedback').style.display='none';$('#next').style.display='none';$('#answers').innerHTML=c.options.map((o,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.i));$$('[data-conf]').forEach(b=>b.classList.toggle('active',+b.dataset.conf===confidence));$('#aiFace').textContent=pe.face;$('#aiName').textContent=pe.name;$('#taunt').textContent=rand(pe.taunts);if(state.mode==='lightning'){let left=10;$('#timerLabel').hidden=false;$('#timerLabel').textContent=`⚡ ${left.toFixed(1)} seconds`;timer=setInterval(()=>{left-=.1;$('#timerLabel').textContent=`⚡ ${Math.max(0,left).toFixed(1)} seconds`;if(left<=0){clearInterval(timer);answer(-1)}},100)}else $('#timerLabel').hidden=true}
$$('[data-conf]').forEach(b=>b.onclick=()=>{confidence=+b.dataset.conf;$$('[data-conf]').forEach(x=>x.classList.toggle('active',x===b))});
function sound(ok){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:160;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.15);o.start();o.stop(c.currentTime+.15);navigator.vibrate?.(ok?25:[35,25,35])}catch{}}
function answer(i){if($('#next').style.display==='block')return;clearInterval(timer);const c=daily[state.round]||fallback[state.round%fallback.length],ok=i===c.answer,base=100*confidence;state.correct+=ok?1:0;state.score+=ok?base:-Math.max(0,(confidence-1)*40);state.marks.push(ok?'🟩':'🟥');const cat=c.category||'Reasoning';state.cats[cat]??={right:0,total:0};state.cats[cat].total++;if(ok)state.cats[cat].right++;$$('.answer').forEach((b,n)=>{b.disabled=true;if(n===c.answer)b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});const pe=persona();$('#feedback').innerHTML=`<b>${ok?'✓ HUMAN 1 — AI 0':'✕ AI GOT YOU'}</b><br>${c.why}<br><br><span class="type">AI replay</span><br>${c.aiTake||c.why}<br><br><b>${pe.face} ${pe.name}:</b> “${rand(ok?pe.win:pe.lose)}”`;$('#feedback').style.display='block';$('#points').textContent=`${Math.max(0,Math.round(state.score))} pts`;$('#next').style.display='block';sound(ok)}
$('#next').onclick=()=>state.round<totalRounds()-1?(state.round++,render()):finish();

function mergeCats(p){p.cats||={};for(const [k,v] of Object.entries(state.cats)){p.cats[k]??={right:0,total:0};p.cats[k].right+=v.right;p.cats[k].total+=v.total}}
function unlockChecks(p){const have=new Set(p.unlocked||[]),logic=p.cats?.Logic?.right||0;const tests={first:p.wins>=1,perfect:p.best>=5,streak7:p.streak>=7,rating1200:p.rating>=1200,plays25:p.plays>=25,logic10:logic>=10,boss:p.rewards?.includes('boss'),impossible:p.rewards?.includes('impossible')};for(const [k,v] of Object.entries(tests))if(v&&!have.has(k)){p.unlocked.push(k);const a=achievementDefs.find(x=>x[0]===k);setTimeout(()=>toast(`${a[3]} Achievement: ${a[1]}`),350)}}
function saveRun(){const p=profile(),total=totalRounds(),countsStreak=state.mode==='daily';if(countsStreak&&p.last!==today){const y=new Date();y.setDate(y.getDate()-1);const yk=y.toISOString().slice(0,10);p.streak=p.last===yk?(p.streak||0)+1:1;p.last=today}p.best=Math.max(p.best||0,state.mode==='daily'?state.correct:0);p.plays=(p.plays||0)+1;p.wins=(p.wins||0)+(state.correct>=Math.ceil(total*.8)?1:0);mergeCats(p);const old=p.rating||1000,ranked=['daily','boss','impossible'].includes(state.mode),change=ranked?Math.round((state.correct/total-.55)*54):0;p.rating=Math.max(600,old+change);const xpGain=Math.max(20,Math.round(Math.max(0,state.score)*.45)+state.correct*15);p.xp=(p.xp||0)+xpGain;p.rewards||=[];if(state.mode==='boss'&&state.correct>=8&&!p.rewards.includes('boss'))p.rewards.push('boss');if(state.mode==='impossible'&&state.correct===1&&!p.rewards.includes('impossible'))p.rewards.push('impossible');unlockChecks(p);saveProfile(p);return{p,old,change,xpGain}}
async function finish(){clearInterval(timer);const {p,old,change,xpGain}=saveRun(),total=totalRounds();$('#final').textContent=`${state.correct}/${total}`;$('#sharegrid').textContent=state.marks.join('');$('#verdict').textContent=state.correct===total?'Perfect. Machines humbled.':state.correct/total>=.8?'Humanity survives.':state.correct/total>=.6?'Barely human enough.':'AI wins this round.';$('#meta').textContent=`${Math.max(0,Math.round(state.score))} points • ${p.streak||0} day streak • ${persona().name} ${state.correct/total>=.8?'owes you an apology':'is insufferable now'}`;$('#ratingResult').textContent=`${old} → ${p.rating} ${change>=0?'▲':'▼'}${Math.abs(change)}`;$('#xpResult').textContent=`+${xpGain} XP`;$('#xpBar').style.width=`${((p.xp||0)%250)/2.5}%`;renderSkills();renderAchievements();show('result');await loadBoard();if(state.mode==='daily')submitScore();if(p.plays%5===0)setTimeout(openReward,650);refresh()}
async function submitScore(){try{await fetch('/api/scores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dayKey:today,displayName:localStorage.getItem('beatAIName')||'Player',score:Math.max(0,Math.round(state.score)),correct:state.correct,elapsedMs:Date.now()-state.start,fingerprint:localStorage.getItem('beatAIFingerprint')||''})})}catch{}}
async function loadBoard(){let rows=[];try{const r=await fetch('/api/scores?date='+today);const d=await r.json();rows=d.leaderboard||[]}catch{}if(!rows.length)rows=[{display_name:'NovaKite',score:500},{display_name:'HumanAfterAll',score:500},{display_name:'NoPromptNeeded',score:450}];$('#leaderboard').innerHTML=rows.slice(0,10).map((r,i)=>`<div class="row"><span>${i===0?'<span class="crown">👑</span>':'#'+(i+1)} ${r.display_name}</span><b>${r.score} pts</b></div>`).join('')}
function renderSkills(){const p=profile(),cats=['Logic','Patterns','Language','Reasoning','Visual'];$('#skills').innerHTML=cats.map(k=>{const v=p.cats?.[k]||{right:0,total:0},pct=v.total?Math.round(v.right/v.total*100):0;return`<div class="skillrow"><label><b>${k}</b><span>${pct}%</span></label><div class="meter"><div style="width:${pct}%"></div></div></div>`}).join('');const played=Object.values(p.cats||{}).reduce((a,v)=>a+v.total,0);$('#skillSummary').textContent=played?`${played} questions analyzed`:'learning you…'}
function renderAchievements(){const p=profile(),u=new Set(p.unlocked||[]);$('#achievements').innerHTML=achievementDefs.map(a=>`<div class="achievement ${u.has(a[0])?'':'locked'}"><b>${a[3]} ${a[1]}</b>${a[2]}</div>`).join('');$('#achievementCount').textContent=`${u.size}/${achievementDefs.length} unlocked`}
function renderFeed(){const p=profile(),names=['Maya','Jax','Rina','Toby','Kira'],events=[`${names[p.plays%5]} just beat ${persona().name} 5/5`,`${names[(p.streak||1)%5]} reached a ${Math.max(3,(p.streak||1)+4)} day streak`,`Brazil took today’s crown 👑`,`Someone just solved the 1% question`,`A human crossed 1400 Arena rating`];$('#feed').innerHTML=events.slice(0,4).map(x=>`<div class="feed-item">🔥 ${x}</div>`).join('')}
function openReward(){const rewards=[['🧠','Neon Brain','Animated profile aura unlocked.'],['⚡','Static Shock','Lightning victory effect unlocked.'],['👾','Glitch Frame','A chaotic little profile frame.'],['🏆','Chrome Crown','Because subtlety is for people ranked lower.']],r=rand(rewards);$('#rewardEmoji').textContent=r[0];$('#rewardName').textContent=r[1];$('#rewardDesc').textContent=r[2];$('#rewardModal').classList.add('open');const p=profile();if(!p.rewards.includes(r[1]))p.rewards.push(r[1]);saveProfile(p)}
function openProfile(){const p=profile();$('#profileTitle').textContent=titleFor(p.xp||0);$('#profileMeta').textContent=`Level ${levelFor(p.xp||0)} • ${p.rating||1000} Arena • ${p.streak||0} day streak`;$('#profileContent').innerHTML=`<div class="card"><b>Season ${seasonNo}</b><p class="muted small">${p.xp||0} XP • Next level in ${250-((p.xp||0)%250)} XP</p>${(p.rewards||[]).map(x=>`<div class="feed-item">✨ ${x}</div>`).join('')||'<span class="muted small">Win battles and open mystery crates.</span>'}</div>`;$('#profileModal').classList.add('open')}

function shareText(){return`Beat AI — ${state.mode.toUpperCase()}\n${state.marks.join('')} ${state.correct}/${totalRounds()}\n🧠 ${profile().rating} Arena • 🔥 ${profile().streak||0}\nCan you beat me?\nhttps://quantum-adventures.vercel.app`}
async function share(){const text=shareText();try{if(navigator.share)await navigator.share({title:'Beat AI',text});else{await navigator.clipboard.writeText(text);toast('Challenge copied!')}}catch{}}

async function beginCheckout(){const email=prompt('Email for your Beat AI Pro receipt and account recovery:','')||'';if(!email.includes('@'))return toast('Enter a valid email to continue');$('#upgradeBtn').disabled=true;$('#upgradeBtn').textContent='OPENING SECURE CHECKOUT…';try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'Checkout unavailable');localStorage.setItem('beatAIEmail',email);location.href=d.url}catch(e){toast(e.message);$('#upgradeBtn').disabled=false;$('#upgradeBtn').textContent='GO PRO — $5.99/MONTH'}}
async function verifySession(sessionId){try{const r=await fetch('/api/billing-status?session_id='+encodeURIComponent(sessionId));const d=await r.json();if(r.ok&&d.active){setBilling({tier:'pro',customerId:d.customerId,subscriptionId:d.subscriptionId,status:d.status,verifiedAt:Date.now()});toast('Beat AI Pro unlocked ✦');history.replaceState({},'',location.pathname)}else toast(d.error||'Could not verify subscription')}catch{toast('Could not verify subscription')}}
async function openPortal(){const b=billing();if(!b.customerId)return toast('No Stripe customer found yet');try{const r=await fetch('/api/billing-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:b.customerId})});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'Billing portal unavailable');location.href=d.url}catch(e){toast(e.message)}}

$('#play').onclick=()=>start('daily');$('#again').onclick=()=>start('practice');$('#practiceBtn').onclick=()=>start('practice');$('#lightningBtn').onclick=()=>start('lightning');$('#bossBtn').onclick=()=>start('boss');$('#impossibleBtn').onclick=()=>start('impossible');$('#friendBtn').onclick=share;$('#share').onclick=share;$('#profileBtn').onclick=openProfile;$('#proBtn').onclick=()=>$('#proCard').scrollIntoView({behavior:'smooth',block:'center'});$('#upgradeBtn').onclick=beginCheckout;$('#manageBtn').onclick=openPortal;$('#restoreBtn').onclick=()=>toast(localStorage.getItem('beatAIEmail')?'Sign-in restore is the next account step.':'No prior purchase found on this device.');$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
const qp=new URLSearchParams(location.search);if(qp.get('billing')==='success'&&qp.get('session_id'))verifySession(qp.get('session_id'));if(qp.get('billing')==='cancelled')toast('Checkout cancelled — no charge made');
refresh();renderAchievements();loadDaily();
