/* Reviewed instant-play questions. Generated daily/fresh packs still use the existing APIs. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BeatAIQuestions=api;})(typeof window==='object'?window:this,function(){
  'use strict';
  const rows=[
    ['Science','Which planet has a day longer than its year?',['Venus','Earth','Mars','Jupiter'],0,'Venus takes about 243 Earth days to rotate, but about 225 to orbit the Sun.'],
    ['Science','Which is a mammal?',['Shark','Octopus','Dolphin','Penguin'],2,'Dolphins breathe air and nurse their young.'],
    ['Science','What travels fastest through a vacuum?',['Sound','Light','A rocket','A shock wave'],1,'Light travels through a vacuum at about 300,000 kilometres per second.'],
    ['Science','Which metal is liquid at ordinary room temperature?',['Iron','Mercury','Copper','Aluminium'],1,'Mercury melts below room temperature.'],
    ['Science','What gives plants their green colour?',['Chlorophyll','Iron','Glucose','Carbon dioxide'],0,'Chlorophyll absorbs light used in photosynthesis.'],
    ['Science','Which part of an atom carries a negative charge?',['Proton','Neutron','Electron','Nucleus'],2,'Electrons carry a negative electric charge.'],
    ['Science','Which animal has three hearts?',['Octopus','Elephant','Crocodile','Eagle'],0,'An octopus has two hearts serving its gills and one serving the body.'],
    ['Science','Sound cannot travel through which of these?',['Steel','Water','Air','A vacuum'],3,'Sound needs matter to transmit its vibrations.'],
    ['Science','Which gas makes up most of Earth’s atmosphere?',['Oxygen','Nitrogen','Carbon dioxide','Helium'],1,'Nitrogen makes up about 78% of the atmosphere.'],
    ['Science','At sea level, pure water freezes at what Celsius temperature?',['0°','10°','32°','100°'],0,'Water freezes at 0°C under standard pressure.'],
    ['Science','Which is the largest planet in our solar system?',['Saturn','Neptune','Jupiter','Earth'],2,'Jupiter is the largest by both mass and diameter.'],
    ['Science','A light-year measures what?',['Time','Distance','Brightness','Temperature'],1,'It is the distance light travels in one year.'],
    ['History','Which came first?',['Telephone','Printing press','Television','Airplane'],1,'The printing press predates the other inventions by centuries.'],
    ['History','The Rosetta Stone helped scholars decipher what?',['Morse code','Egyptian hieroglyphs','Binary','Viking runes'],1,'Its parallel inscriptions helped unlock Egyptian hieroglyphs.'],
    ['History','Who was the first person to walk on the Moon?',['Yuri Gagarin','Buzz Aldrin','Neil Armstrong','John Glenn'],2,'Neil Armstrong stepped onto the Moon during Apollo 11 in 1969.'],
    ['History','Which civilisation built Machu Picchu?',['Inca','Roman','Ancient Egyptian','Viking'],0,'Machu Picchu was built by the Inca in the Andes.'],
    ['History','Which city was buried by Mount Vesuvius in AD 79?',['Athens','Pompeii','Carthage','Troy'],1,'The eruption buried Pompeii and neighbouring settlements.'],
    ['History','The Magna Carta was first issued in which year?',['1066','1215','1492','1776'],1,'King John issued the Magna Carta in 1215.'],
    ['History','Who became South Africa’s president in 1994?',['Nelson Mandela','Desmond Tutu','Kofi Annan','Julius Nyerere'],0,'Nelson Mandela became president after the 1994 democratic election.'],
    ['History','Which ancient city gave its name to a marathon?',['Sparta','Marathon','Corinth','Thebes'],1,'The modern race commemorates the legend associated with Marathon in Greece.'],
    ['Technology','What does the “B” in USB stand for?',['Byte','Bus','Bridge','Binary'],1,'USB stands for Universal Serial Bus.'],
    ['Technology','How many bits are in a byte?',['2','4','8','16'],2,'A byte consists of eight bits.'],
    ['Technology','Which is a programming language?',['Python','Cobra','Viper','Anaconda'],0,'Python is a programming language; Anaconda is a software distribution.'],
    ['Technology','What does a browser’s refresh button normally do?',['Deletes the site','Reloads the page','Changes your password','Restarts the computer'],1,'Refresh requests and displays the page again.'],
    ['Technology','Which number is binary 101 in decimal?',['3','4','5','6'],2,'101 represents 1×4 + 0×2 + 1×1 = 5.'],
    ['Technology','What is HTML primarily used for?',['Structuring web pages','Charging batteries','Encrypting hard drives','Compressing sound'],0,'HTML describes the structure and content of web pages.'],
    ['Technology','Which unit describes one million hertz?',['Kilohertz','Megahertz','Gigahertz','Terahertz'],1,'The prefix mega means one million.'],
    ['Technology','In computing, RAM is mainly used for what?',['Temporary working memory','Permanent archival storage','Cooling the processor','Displaying pixels'],0,'RAM holds data and instructions currently in use.'],
    ['Logic','You overtake the runner in second place. What place are you in?',['First','Second','Third','Last'],1,'You take the place of the runner you overtook: second.'],
    ['Logic','All glips are blue. No blue objects are round. Can a glip be round?',['Always','Sometimes','No','Only at night'],2,'Being blue excludes being round under these premises.'],
    ['Logic','Two fathers and two sons share three apples, one each. How?',['One apple is split','Grandfather, father, son','Someone gets none','There are four apples'],1,'The middle person is both a father and a son.'],
    ['Logic','A fair coin lands heads five times. Chance of heads next?',['1 in 32','1 in 6','1 in 2','Certain'],2,'Independent flips do not remember previous outcomes.'],
    ['Logic','Which weighs more: 1 kg of steel or 1 kg of feathers?',['Steel','Feathers','They weigh the same','Depends on the shape'],2,'Both quantities have a mass of one kilogram.'],
    ['Logic','A is taller than B. B is taller than C. Who is shortest?',['A','B','C','Cannot tell'],2,'The order is A, then B, then C.'],
    ['Logic','Some artists are pilots. All pilots can fly. What must follow?',['All artists can fly','Some artists can fly','No artists can fly','All pilots are artists'],1,'The artists who are pilots can fly.'],
    ['Logic','A drawer has only red and blue socks. How many draws guarantee a matching colour?',['2','3','4','5'],1,'Even if the first two differ, the third matches one of them.'],
    ['Logic','A clock strikes 3 in 2 seconds. At the same pace, how long for 6 strikes?',['3 seconds','4 seconds','5 seconds','6 seconds'],2,'Three strikes span two intervals; six strikes span five.'],
    ['Logic','If yesterday was Thursday, what day is tomorrow?',['Friday','Saturday','Sunday','Wednesday'],1,'Today is Friday, so tomorrow is Saturday.'],
    ['Reasoning','A $100 jacket is reduced by 20%, then another 20%. Final price?',['$60','$64','$80','$40'],1,'The first reduction leaves $80; 80% of $80 is $64.'],
    ['Reasoning','A bat and ball cost $1.10. The bat costs $1 more. Ball price?',['10¢','5¢','15¢','1¢'],1,'The ball is 5¢ and the bat is $1.05.'],
    ['Reasoning','Which fraction is largest?',['1/2','2/3','3/5','5/8'],1,'2/3 is about 0.667, larger than the other fractions.'],
    ['Reasoning','What is the average of 4, 8 and 12?',['6','8','10','12'],1,'Their sum is 24; dividing by three gives 8.'],
    ['Reasoning','A train covers 120 km in 2 hours. Average speed?',['30 km/h','60 km/h','90 km/h','240 km/h'],1,'Speed equals distance divided by time: 120 ÷ 2 = 60.'],
    ['Reasoning','Which number is both even and prime?',['0','1','2','4'],2,'Two has exactly two positive divisors: 1 and 2.'],
    ['Reasoning','A price rises 50%, then falls 50%. Compared with the start it is…',['Unchanged','25% lower','25% higher','50% lower'],1,'For example, $100 becomes $150, then $75.'],
    ['Reasoning','How many degrees are in a triangle’s interior angles on a flat plane?',['90','180','270','360'],1,'In Euclidean geometry, a triangle’s angles add to 180°.'],
    ['Patterns','What comes next: 2, 6, 12, 20, 30, …?',['36','40','42','60'],2,'The differences are 4, 6, 8, 10; the next is 12.'],
    ['Patterns','What comes next: 1, 1, 2, 3, 5, 8, …?',['10','11','12','13'],3,'Each term is the sum of the previous two.'],
    ['Patterns','What comes next: 81, 27, 9, 3, …?',['0','1','2','6'],1,'Each term is divided by three.'],
    ['Patterns','What comes next: 1, 8, 27, 64, …?',['81','100','125','128'],2,'These are cubes: 1³, 2³, 3³, 4³, then 5³ = 125.'],
    ['Patterns','Complete the sequence: AZ, BY, CX, …',['DW','DX','EW','DY'],0,'The first letter moves forward and the second moves backward.'],
    ['Patterns','What comes next: 2, 3, 5, 7, 11, …?',['12','13','14','15'],1,'These are consecutive prime numbers.'],
    ['Patterns','What comes next: 100, 50, 25, 12.5, …?',['0','5','6.25','10'],2,'Each term is half the previous term.'],
    ['Patterns','Which number breaks this doubling pattern: 3, 6, 12, 25, 48?',['6','12','25','48'],2,'The fourth number should be 24.'],
    ['Language','Which word is a palindrome?',['Radar','Radio','Reader','Random'],0,'Radar reads the same backward and forward.'],
    ['Language','Which word means the opposite of “scarce”?',['Rare','Limited','Abundant','Hidden'],2,'Abundant means available in large quantities.'],
    ['Language','“The wind whispered” is an example of what?',['Personification','A literal statement','An acronym','A rhyme'],0,'It gives a human action to the wind.'],
    ['Language','Which pair consists of homophones in standard English?',['Sea / see','Cat / dog','Hot / cold','Read / road'],0,'Sea and see sound alike but have different meanings.'],
    ['Language','Which is the correctly spelled word?',['Accomodate','Acommodate','Accommodate','Acomodate'],2,'Accommodate has two c’s and two m’s.'],
    ['Language','What does the prefix “bi-” mean in “bicycle”?',['One','Two','Three','Many'],1,'A bicycle has two wheels.'],
    ['Language','Which is an anagram of “listen”?',['Silent','Listed','Lesson','Little'],0,'Listen and silent use exactly the same letters.'],
    ['Language','Which word is the odd one out by meaning?',['Swift','Rapid','Quick','Heavy'],3,'The other three describe speed.'],
    ['Sports','In basketball, a shot from the free-throw line is worth…',['1 point','2 points','3 points','4 points'],0,'A made free throw earns one point.'],
    ['Sports','In tennis, what does “love” mean in the score?',['Zero','One','Deuce','Advantage'],0,'Love represents zero points.'],
    ['Sports','How many players per side are on court in standard volleyball?',['4','5','6','7'],2,'Indoor volleyball is played with six players per side.'],
    ['Sports','What is three under par on a single golf hole called?',['Birdie','Eagle','Albatross','Bogey'],2,'An albatross is three strokes under par.'],
    ['Sports','How many rings are in the Olympic symbol?',['4','5','6','7'],1,'The Olympic symbol has five interlaced rings.'],
    ['Sports','Which chess piece moves in an L shape?',['Bishop','Rook','Knight','Queen'],2,'A knight moves two squares along one axis and one along the other.'],
    ['Sports','A standard soccer match has how many minutes before added time?',['60','80','90','100'],2,'Two 45-minute halves total 90 minutes.'],
    ['Sports','In baseball, how many strikes normally make an out?',['2','3','4','5'],1,'Three strikes result in a strikeout.'],
    ['Geography','Which ocean is the largest?',['Atlantic','Indian','Arctic','Pacific'],3,'The Pacific covers more area than any other ocean.'],
    ['Geography','Which country is home to the city of Kyoto?',['China','Japan','Thailand','South Korea'],1,'Kyoto is in Japan.'],
    ['Geography','Which continent has no permanent native human population?',['Europe','Antarctica','Australia','South America'],1,'Antarctica hosts research stations, but has no indigenous human population.'],
    ['Geography','Which city straddles Europe and Asia?',['Madrid','Istanbul','Oslo','Lisbon'],1,'Istanbul lies on both sides of the Bosporus.'],
    ['Geography','Which country is completely surrounded by South Africa?',['Lesotho','Kenya','Ghana','Zambia'],0,'Lesotho is an enclave within South Africa.'],
    ['Geography','Which of these countries has no coastline?',['Portugal','Bolivia','Vietnam','Norway'],1,'Bolivia is landlocked.'],
    ['Geography','The Andes mountain range is in which continent?',['Africa','Europe','South America','Asia'],2,'The Andes run along the western edge of South America.'],
    ['Geography','Which line divides Earth into Northern and Southern Hemispheres?',['Prime Meridian','Equator','Tropic of Cancer','Arctic Circle'],1,'The Equator is at 0° latitude.'],
    ['Culture','How many strings does a standard violin have?',['4','5','6','8'],0,'A standard violin has four strings.'],
    ['Culture','Who painted The Starry Night?',['Claude Monet','Vincent van Gogh','Pablo Picasso','Leonardo da Vinci'],1,'Vincent van Gogh painted The Starry Night in 1889.'],
    ['Culture','Which instrument has keys, pedals and strings?',['Flute','Trumpet','Piano','Clarinet'],2,'A piano’s keys cause hammers to strike strings.'],
    ['Culture','Who wrote Frankenstein?',['Mary Shelley','Jane Austen','Virginia Woolf','Emily Brontë'],0,'Mary Shelley’s Frankenstein was first published in 1818.'],
    ['Culture','In music, “a cappella” means singing…',['Without instruments','Very loudly','In a whisper','Without lyrics'],0,'A cappella is vocal music without instrumental accompaniment.'],
    ['Culture','Which artist is associated with melting clocks?',['Salvador Dalí','Andy Warhol','Henri Matisse','Rembrandt'],0,'Melting clocks appear in Dalí’s The Persistence of Memory.'],
    ['Culture','Which colour combines with red to make purple in traditional paint mixing?',['Green','Yellow','Blue','Orange'],2,'Red and blue pigments combine to make purple.'],
    ['Culture','Which is a percussion instrument?',['Oboe','Cello','Timpani','Saxophone'],2,'Timpani are kettledrums.']
  ];
  const bank=rows.map(([category,q,options,answer,why])=>({type:'ARENA',category,q,options,answer,why,aiTake:why,difficulty:2}));
  function canon(q){return String(q||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
  function valid(c){return !!c&&typeof c.q==='string'&&c.q.length>0&&c.q.length<=500&&Array.isArray(c.options)&&c.options.length===4&&c.options.every(x=>typeof x==='string'&&x.length>0&&x.length<=300)&&new Set(c.options).size===4&&Number.isInteger(c.answer)&&c.answer>=0&&c.answer<4&&typeof c.why==='string';}
  function select(pool,count,history=[],random=Math.random){
    const seen=new Set(history.map(canon)), own=new Set();
    const unique=pool.filter(c=>{const key=canon(c?.q);if(!valid(c)||seen.has(key)||own.has(key))return false;own.add(key);return true;});
    for(let i=unique.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[unique[i],unique[j]]=[unique[j],unique[i]];}
    // Interleave categories instead of serving a wall of arithmetic.
    const chosen=[];while(unique.length&&chosen.length<count){let index=unique.findIndex(c=>c.category!==chosen.at(-1)?.category);if(index<0)index=0;chosen.push(unique.splice(index,1)[0]);}return chosen;
  }
  return {bank,canon,valid,select};
});
