(()=>{
  'use strict';
  const SITE='https://beatai.games',byId=id=>document.getElementById(id);
  function target(){const b=state.battle;if(state.finished&&b)return {correct:state.correct,total:state.marks.length,outcome:b.outcome,rival:b.rival.id,name:b.rival.name,combo:b.bestCombo,hp:b.human,mode:state.mode};return {correct:0,total:0,outcome:'invite',rival:'static',name:'STATIC',combo:0,hp:0,mode:'arena'};}
  function playerName(){try{return (localStorage.getItem('beatAIName')||'A human').slice(0,28);}catch{return 'A human';}}
  function challengeUrl(){const t=target(),u=new URL(SITE);u.searchParams.set('challenge','1');u.searchParams.set('rival',t.rival);if(t.total){u.searchParams.set('beat',`${t.correct}-${t.total}`);u.searchParams.set('outcome',t.outcome);}return u.toString();}
  function cardUrl(){const t=target(),u=new URL('/api/share-card',location.origin);for(const [k,v]of Object.entries({name:playerName(),score:t.correct,total:t.total||7,outcome:t.outcome,rival:t.rival,combo:t.combo,hp:t.hp}))u.searchParams.set(k,String(v));return u.toString();}
  function shareCopy(){const t=target();if(t.outcome==='invite')return `A brain. A grudge. A battle. Can you beat the machine? ${challengeUrl()}`;const lead=t.outcome==='win'?`HUMAN 1 — AI 0. ${t.name} defeated.`:`${t.name} won this one. I'm coming back.`;return `${lead}\n${t.correct}/${t.total} correct · ${t.combo}-answer combo · ${t.hp} HP left.\nQuestions are your weapon. ${challengeUrl()}`;}
  function refreshSharePreview(){const img=byId('sharePreview');if(!img||!state.finished)return;img.src=cardUrl();img.alt=`${target().outcome==='win'?'Victory':'Defeat'} against ${target().name}: ${target().correct}/${target().total} correct`;img.onerror=()=>{img.hidden=true;toast('Share image unavailable. Your text challenge still works.');};img.onload=()=>{img.hidden=false;};}
  async function copy(){try{await navigator.clipboard.writeText(shareCopy());toast('Challenge copied. Pick your human.');}catch{toast('Copy unavailable in this browser. Use Share Result instead.');}}
  async function nativeShare(){try{if(navigator.share)await navigator.share({title:'BeatAI — Human vs AI',text:shareCopy()});else await copy();}catch(e){if(e.name!=='AbortError')toast('Sharing is unavailable. Try Copy Challenge.');}}
  function shareTo(network){const url=challengeUrl(),text=shareCopy(),enc=encodeURIComponent;const links={x:`https://twitter.com/intent/tweet?text=${enc(text)}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${enc(url)}`,reddit:`https://www.reddit.com/submit?url=${enc(url)}&title=${enc(target().outcome==='win'?'Human 1 — AI 0':'Can you beat this AI rival?')}`,whatsapp:`https://wa.me/?text=${enc(text)}`};if(network==='copy')return copy();if(links[network])window.open(links[network],'_blank','noopener,noreferrer');}
  async function downloadCard(){
    const button=byId('downloadCard');button.disabled=true;
    try{const r=await fetch(cardUrl());if(!r.ok)throw new Error();const svg=await r.blob(),source=URL.createObjectURL(svg),img=new Image();
      try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=source;});const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;canvas.getContext('2d').drawImage(img,0,0,1200,630);const png=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!png)throw new Error();const url=URL.createObjectURL(png),a=document.createElement('a');a.href=url;a.download=`beatai-${target().rival}-${target().outcome}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}finally{URL.revokeObjectURL(source);}
    }catch{toast('Could not save the image. Your text challenge is still available.');}finally{button.disabled=false;}
  }
  function incoming(){const q=new URLSearchParams(location.search);if(q.get('challenge')!=='1')return;const match=(q.get('beat')||'').match(/^(\d{1,2})-(\d{1,2})$/),r=BeatAIRivals.list.find(x=>x.id===q.get('rival'))||BeatAIRivals.list[0];byId('challengeBanner').hidden=false;byId('challengeHeadline').textContent=`A human called out ${r.name}.`;byId('challengeDetail').textContent=match&&+match[1]<=+match[2]&&+match[2]>0?`Their score: ${+match[1]}/${+match[2]}. Face the arena with your own questions.`:'Questions are your weapon. Your turn to fight.';byId('acceptChallengeBtn').onclick=()=>{byId('challengeBanner').hidden=true;start('arena',available(r)?r.id:'static');};}
  byId('share').onclick=nativeShare;byId('friendBtn').onclick=()=>{state.finished?nativeShare():navigator.share?navigator.share({title:'BeatAI',text:`Can you beat the machine? ${SITE}`}).catch(()=>{}):navigator.clipboard.writeText(`Can you beat the machine? ${SITE}`).then(()=>toast('Arena invite copied.')).catch(()=>toast('Open beatai.games to invite a friend.'));};
  byId('downloadCard').onclick=downloadCard;document.querySelectorAll('[data-social]').forEach(b=>b.onclick=()=>shareTo(b.dataset.social));window.addEventListener('beat-ai:result-ready',refreshSharePreview);incoming();
  window.BeatAISocial={challengeUrl,cardUrl,shareCopy,shareTo,refreshSharePreview};
})();
