(()=>{
  const SITE='https://beatai.games';
  const byId=id=>document.getElementById(id);
  if(!document.querySelector('link[href="/social.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/social.css';document.head.appendChild(link)}
  function referralId(){let id=localStorage.getItem('beatAIReferralId');if(!id){const raw=(crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/-/g,'');id=raw.slice(0,10).toLowerCase();localStorage.setItem('beatAIReferralId',id)}return id}
  function playerName(){return (localStorage.getItem('beatAIName')||'A human').slice(0,32)}
  function incomingChallenge(){try{return JSON.parse(localStorage.getItem('beatAIIncomingChallenge')||'null')}catch{return null}}
  function currentTarget(){try{if(state&&Array.isArray(state.marks)&&state.marks.length)return{correct:state.correct,total:(state.roundLimit||state.marks.length||totalRounds()),mode:state.mode,marks:state.marks.join('')}}catch{}const p=typeof profile==='function'?profile():{best:0};return{correct:p.best||0,total:5,mode:'daily',marks:''}}
  function profileData(){try{return typeof profile==='function'?profile():{}}catch{return{}}}
  function shareKind(){const t=currentTarget(),p=profileData(),incoming=incomingChallenge();if(incoming&&Date.now()-(incoming.openedAt||0)<86400000)return'challenge';if(t.correct===t.total)return'achievement';if((p.streak||0)>=7)return'streak';return'victory'}
  function cardUrl(){const t=currentTarget(),p=profileData(),u=new URL('/api/share-card',SITE);u.searchParams.set('name',playerName());u.searchParams.set('score',t.correct);u.searchParams.set('total',t.total);u.searchParams.set('marks',t.marks||'');u.searchParams.set('streak',p.streak||0);u.searchParams.set('rating',p.rating||1000);u.searchParams.set('kind',shareKind());return u.toString()}
  function challengeUrl(){const t=currentTarget(),u=new URL(SITE);u.searchParams.set('challenge','1');u.searchParams.set('beat',`${t.correct}-${t.total}`);u.searchParams.set('mode',t.mode||'daily');u.searchParams.set('ref',referralId());u.searchParams.set('from',playerName());u.searchParams.set('card',shareKind());u.searchParams.set('score',t.correct);u.searchParams.set('total',t.total);return u.toString()}
  function shareCopy(){const t=currentTarget(),p=profileData(),grid=t.marks?`\n${t.marks} ${t.correct}/${t.total}`:`\nScore: ${t.correct}/${t.total}`;const kind=shareKind();const lead=kind==='challenge'?'I accepted a Beat AI challenge.':t.correct===t.total?'Perfect run — I beat AI today.':`I beat AI today: ${t.correct}/${t.total}.`;return`${lead}${grid}\n🧠 ${p.rating||1000} Arena • 🔥 ${p.streak||0} day streak\nThink you can do better? ${challengeUrl()}`}
  function bumpShare(network){const key='beatAISocialStats',s=JSON.parse(localStorage.getItem(key)||'{}');s[network]=(s[network]||0)+1;s.total=(s.total||0)+1;s.lastSharedAt=Date.now();localStorage.setItem(key,JSON.stringify(s))}
  function popup(url){window.open(url,'beat-ai-share','popup,width=720,height=640,noopener,noreferrer')}
  async function nativeShare(){const text=shareCopy(),url=challengeUrl();try{if(navigator.share){await navigator.share({title:'Beat AI Result',text,url});bumpShare('native');return}await navigator.clipboard.writeText(text);bumpShare('copy');window.toast?.('Result copied — send it anywhere 🔗')}catch(e){if(e?.name!=='AbortError')window.toast?.('Share cancelled')}}
  async function shareTo(network){const text=shareCopy(),url=challengeUrl(),enc=encodeURIComponent;if(network==='x')popup(`https://twitter.com/intent/tweet?text=${enc(text)}`);else if(network==='facebook')popup(`https://www.facebook.com/sharer/sharer.php?u=${enc(url)}`);else if(network==='reddit')popup(`https://www.reddit.com/submit?url=${enc(url)}&title=${enc('I beat AI today — can you?')}`);else if(network==='whatsapp')popup(`https://wa.me/?text=${enc(text)}`);else if(network==='copy'){try{await navigator.clipboard.writeText(text);window.toast?.('Share link copied 🔗')}catch{window.toast?.('Could not copy link')}}bumpShare(network)}
  function readIncomingChallenge(){const q=new URLSearchParams(location.search);if(q.get('challenge')!=='1')return;const beat=(q.get('beat')||'').match(/^(\d+)-(\d+)$/),from=(q.get('from')||'A human').slice(0,32),ref=(q.get('ref')||'').slice(0,32);if(ref&&ref!==referralId())localStorage.setItem('beatAIInvitedBy',ref);if(!beat)return;const correct=Math.max(0,+beat[1]),total=Math.max(1,+beat[2]);const banner=byId('challengeBanner');byId('challengeHeadline').textContent=`${from} challenged you.`;byId('challengeDetail').textContent=`Beat ${correct}/${total}. No pressure. Your dignity is merely on the line.`;banner.hidden=false;localStorage.setItem('beatAIIncomingChallenge',JSON.stringify({from,correct,total,ref,openedAt:Date.now()}));byId('acceptChallengeBtn').onclick=()=>{banner.hidden=true;try{start('daily')}catch{byId('play')?.click()}}}
  function addCasinoEntry(){
    if(document.getElementById('casinoLaunchCard'))return;
    const home=byId('home'),modegrid=home?.querySelector('.modegrid.visual-modes');
    if(!modegrid)return;
    const card=document.createElement('a');
    card.id='casinoLaunchCard';
    card.href='/casino';
    card.setAttribute('aria-label','Open Beat AI Casino');
    card.innerHTML='<div class="casino-kicker">NEW · SOCIAL CASINO</div><div class="casino-row"><div class="casino-icon">♠</div><div><strong>Beat AI Casino</strong><span>Blackjack, AI Poker & rival personalities</span></div><div class="casino-arrow">→</div></div><div class="casino-foot">Virtual Royale Chips only · no cash value · no cash-out</div>';
    const style=document.createElement('style');
    style.textContent='#casinoLaunchCard{display:block;grid-column:1/-1;text-decoration:none;color:#fff;background:radial-gradient(circle at 18% 10%,rgba(246,200,95,.22),transparent 32%),linear-gradient(135deg,#17111f,#0c1118 58%,#10251e);border:1px solid rgba(246,200,95,.5);border-radius:22px;padding:18px;margin-top:2px;box-shadow:0 16px 45px rgba(0,0,0,.28);transition:.18s transform,.18s border-color}#casinoLaunchCard:hover{transform:translateY(-2px);border-color:#f6c85f}.casino-kicker{font-size:10px;letter-spacing:1.6px;font-weight:950;color:#f6c85f;margin-bottom:10px}.casino-row{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center}.casino-icon{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;font-size:28px;background:linear-gradient(145deg,#f6c85f,#9b6fff);color:#07090d;box-shadow:0 10px 25px rgba(155,111,255,.22)}.casino-row strong{display:block;font-size:20px;letter-spacing:-.4px}.casino-row span{display:block;color:#aab2bf;font-size:12px;line-height:1.35;margin-top:3px}.casino-arrow{font-size:28px;color:#f6c85f}.casino-foot{font-size:10px;color:#788390;margin-top:12px;padding-top:10px;border-top:1px solid rgba(255,255,255,.08)}';
    document.head.appendChild(style);
    modegrid.appendChild(card);
  }
  function wire(){byId('share')&&(byId('share').onclick=nativeShare);byId('friendBtn')&&(byId('friendBtn').onclick=nativeShare);document.querySelectorAll('[data-social]').forEach(btn=>btn.onclick=()=>shareTo(btn.dataset.social));const preview=byId('sharePreview');if(preview){preview.src=cardUrl();preview.alt='Beat AI personalized share preview'}readIncomingChallenge();addCasinoEntry()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
  window.BeatAISocial={challengeUrl,cardUrl,shareCopy,shareTo};
})();