const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Q=require('../question-bank');
function setup(storage={},fetchImpl){const data=new Map(Object.entries(storage));const ctx={window:{crypto:{randomUUID:()=> 'unique'}},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},BeatAIQuestions:Q,AbortController,DOMException,setTimeout,clearTimeout,fetch:fetchImpl,billing:()=>({tier:'free'}),profile:()=>({rating:1000,cats:{}})};ctx.window.window=ctx.window;vm.createContext(ctx);vm.runInContext(fs.readFileSync('infinite-replay.js','utf8'),ctx);return {packs:ctx.window.BeatAIPacks,data,ctx};}
test('legacy question history migrates without losing deduplication',()=>{const {packs}=setup({beatAIRecentQuestions:JSON.stringify(['Question one','Question two'])});assert.equal(packs.history().length,2);packs.remember([{q:'Question ONE!'}]);assert.equal(packs.history().length,2);});
test('pack allowance is preserved and capped at three',()=>{const {packs}=setup({beatAIFreePacksUsed:'2'});assert.equal(packs.left(),1);packs.consume();packs.consume();assert.equal(packs.used(),3);assert.equal(packs.left(),0);});
test('building a 15-question pack rejects cross-part duplicates, and does not consume allowance',async()=>{let calls=0;const {packs}=setup({},async()=>({ok:true,json:async()=>({source:'generated',challenges:Q.bank.slice(calls++===0?0:5,calls===1?5:10)})}));await assert.rejects(packs.buildPack(3,'test'));assert.equal(packs.used(),0);assert.equal(packs.history().length,0);});
test('successful generation keeps unused questions out of seen history',async()=>{let calls=0;const {packs}=setup({},async()=>{const n=calls++*5;return {ok:true,json:async()=>({source:'generated',challenges:Q.bank.slice(n,n+5)})};});const result=await packs.buildPack(3,'test');assert.equal(result.challenges.length,15);assert.equal(packs.history().length,0);packs.remember([result.challenges[0]]);assert.equal(packs.history().length,1);});
test('network failures and cancellation do not charge free packs',async()=>{const {packs}=setup({},async()=>{throw new Error('offline');});await assert.rejects(packs.buildPack(3,'test'));assert.equal(packs.used(),0);const c=new AbortController();c.abort();await assert.rejects(packs.buildPack(3,'test',{signal:c.signal}));assert.equal(packs.used(),0);});
test('inactive subscription downgrades; network outage does not revoke Pro',async()=>{const {packs,ctx}=setup({},async()=>({ok:true,json:async()=>({active:false,status:'canceled'})}));ctx.billing=()=>({tier:'pro',subscriptionId:'test-sub'});let update;ctx.setBilling=x=>{update=x;};await packs.syncProEntitlement();assert.equal(update.tier,'free');update=null;ctx.fetch=async()=>{throw new Error('offline');};await packs.syncProEntitlement();assert.equal(update,null);});
