create table if not exists public.daily_challenges (
  day_key date primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  day_key date not null,
  display_name text not null check (char_length(display_name) between 1 and 24),
  score integer not null check (score between 0 and 5000),
  correct integer not null check (correct between 0 and 5),
  elapsed_ms integer not null default 0 check (elapsed_ms between 0 and 3600000),
  fingerprint text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists scores_day_rank_idx
  on public.scores(day_key, score desc, elapsed_ms asc);

create index if not exists scores_fingerprint_day_idx
  on public.scores(day_key, fingerprint);

alter table public.daily_challenges enable row level security;
alter table public.scores enable row level security;

-- Server-side Vercel functions use the service-role key. No anonymous table
-- policies are intentionally created, so browser clients cannot write scores
-- or tamper with generated daily challenge payloads directly.
