const FALLBACK=[
{type:'LOGIC DUEL',category:'Logic',q:'A farmer has 17 sheep. All but 9 run away. How many remain?',sub:'The obvious arithmetic answer is a trap.',options:['8','9','17','26'],answer:1,why:'“All but 9” means 9 stayed.',aiTake:'A language model can over-weight the subtraction cue instead of parsing the phrase precisely.'},
{type:'PATTERN HACK',category:'Patterns',q:'What comes next: 1, 11, 21, 1211, 111221, ?',sub:'Read the previous number aloud.',options:['312211','122211','1113213211','311221'],answer:0,why:'111221 is three 1s, two 2s, one 1 → 312211.',aiTake:'This is descriptive sequencing, not ordinary arithmetic.'},
{type:'TRUTH TEST',category:'Reasoning',q:'Which statement is definitely true?',sub:'No browsing. Just reasoning.',options:['Every prime is odd.','Some even numbers are prime.','Every square is even.','Negative numbers cannot be squared.'],answer:1,why:'2 is both even and prime.',aiTake:'Universal claims fall apart on counterexamples; 2 settles this one.'},
{type:'AI LANGUAGE TRAP',category:'Language',q:'Which phrase is the stronger clue text may be AI-written?',sub:'Neither proves anything alone.',options:['I dunno, it felt weird.','In today’s rapidly evolving landscape…','Honestly, I missed the bus.','My dog ate the corner of it.'],answer:1,why:'That polished generic transition is common in generated prose.',aiTake:'Generic high-polish framing often carries less concrete information.'},
{type:'HUMAN OR AI',category:'Language',q:'Which line sounds more AI-generated?',sub:'Pick the more generic polished sentence.',options:['I forgot my umbrella again. Classic me.','The rainfall created a profoundly atmospheric experience that enhanced my emotional connection to the environment.','My socks are soaked.','I ran back for the umbrella and missed the train.'],answer:1,why:'The abstract, over-polished language is the stronger clue.',aiTake:'The sentence stacks abstractions and emotional filler instead of concrete detail.'}
];
const json=(res,status,body)=>{res.status(status).setHeader('Cache-Control','s-maxage=3600, stale-while-revalidate=86400').json(body)};
async function cached(day){const u=process.env.SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)return null;const r=await fetch(`${u}/rest/v1/daily_challenges?day_key=eq.${day}&select=payload&limit=1`,{headers:{apikey:k,Authorization:`Bearer ${k}`}});if(!r.ok)return null;const rows=await r.json();return rows?.[0]?.payload||null}
async function save(day,payload){const u=process.env.SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)return;await fetch(`${u}/rest/v1/daily_challenges?on_conflict=day_key`,{method:'POST',headers:{apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({day_key:day,payload})})}
function valid(list){return Array.isArray(list)&&list.length===5&&list.every(x=>typeof x.type==='string'&&typeof x.category==='string'&&typeof x.q==='string'&&Array.isArray(x.options)&&x.options.length===4&&Number.isInteger(x.answer)&&x.answer>=0&&x.answer<=3&&typeof x.why==='string'&&typeof x.aiTake==='string')}
async function generate(day){const key=process.env.OPENAI_API_KEY;if(!key)return FALLBACK;const prompt=`Create exactly 5 short multiple-choice challenges for Beat AI on ${day}. The player is competing against a witty AI opponent. Mix logic traps, pattern recognition, lateral reasoning, human-vs-AI language detection, and truth tests. Each item must contain: type, category (one of Logic, Patterns, Language, Reasoning, Visual), q, sub, options (exactly four strings), answer (integer 0-3), why, and aiTake. The why field explains the correct answer in one concise sentence. The aiTake field explains in one concise sentence what reasoning trap an AI or human might fall into, without claiming hidden chain-of-thought. Keep each playable in under 30 seconds. Avoid politics, medical advice, sexual content, copyrighted trivia, subjective answers, and anything requiring web browsing. Return only JSON: {"challenges":[...]}.`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:prompt,text:{format:{type:'json_object'}}})});if(!r.ok)throw new Error(`OpenAI ${r.status}`);const d=await r.json();const text=d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'';const list=JSON.parse(text).challenges;if(!valid(list))throw new Error('Invalid challenge set');return list}
module.exports=async(req,res)=>{if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});const day=/^\d{4}-\d{2}-\d{2}$/.test(req.query?.date||'')?req.query.date:new Date().toISOString().slice(0,10);try{const hit=await cached(day);if(hit&&valid(hit))return json(res,200,{dayKey:day,challenges:hit,source:'cache'});const challenges=await generate(day);await save(day,challenges).catch(()=>{});return json(res,200,{dayKey:day,challenges,source:process.env.OPENAI_API_KEY?'generated':'fallback'})}catch(e){return json(res,200,{dayKey:day,challenges:FALLBACK,source:'fallback',warning:e.message})}};
