const {list,portrait}=require('../rivals');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
module.exports=async(req,res)=>{
  const q=req.query||{},r=list.find(x=>x.id===q.rival)||list[0],outcome=['win','loss'].includes(q.outcome)?q.outcome:'invite';
  const total=clamp(q.total||7,1,30),score=clamp(q.score,0,total),combo=clamp(q.combo,0,total),hp=clamp(q.hp,0,200),name=esc(String(q.name||'A human').slice(0,28));
  const color=outcome==='loss'?'#ffb48f':'#d5ec87',headline=outcome==='win'?'HUMAN 1. AI 0.':outcome==='loss'?'THE REMATCH IS PERSONAL.':'HUMAN vs MACHINE.';
  const status=outcome==='win'?`${r.name} DEFEATED`:outcome==='loss'?`${r.name} SURVIVES`:'QUESTIONS ARE YOUR WEAPON';
  const art=portrait(r.id).replace('<svg ','<svg x="800" y="170" width="320" height="320" ');
  const stats=outcome==='invite'?'<text x="65" y="365" fill="#edf2e2" font-size="39" font-weight="700">A brain. A grudge. A battle.</text><text x="65" y="427" fill="#aab39e" font-size="24">Answer to attack. Streak to hit harder.</text>':`<text x="65" y="352" fill="#edf2e2" font-size="25">${name} · ${status}</text><text x="65" y="442" fill="${color}" font-size="67" font-weight="900">${score}/${total}</text><text x="320" y="442" fill="${color}" font-size="67" font-weight="900">${combo}</text><text x="562" y="442" fill="${color}" font-size="67" font-weight="900">${hp}</text><text x="65" y="474" fill="#aab39e" font-size="16">CORRECT</text><text x="320" y="474" fill="#aab39e" font-size="16">BEST COMBO</text><text x="562" y="474" fill="#aab39e" font-size="16">HP LEFT</text>`;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#111710"/><rect x="30" y="30" width="1140" height="570" fill="#212b1b" stroke="#5b6b41"/><g font-family="Arial,sans-serif"><text x="65" y="92" fill="${color}" font-size="24" font-weight="800" letter-spacing="3">BEAT AI / HUMAN RESISTANCE</text><path d="M65 127H1135" stroke="#4d5c3d"/><text x="65" y="224" fill="${color}" font-size="${outcome==='loss'?54:78}" font-weight="900" letter-spacing="-2">${headline}</text><text x="68" y="277" fill="#aab39e" font-size="18" letter-spacing="4">${outcome==='win'&&hp<=30?'COMEBACK COMPLETE':outcome==='win'&&score===total?'PERFECT FIGHT':outcome==='loss'?'NOT OVER. JUST ROUND ONE.':'KNOWLEDGE IS A CONTACT SPORT.'}</text>${stats}${art}<rect x="65" y="529" width="1070" height="48" fill="${color}"/><text x="600" y="561" text-anchor="middle" fill="#1a2212" font-size="23" font-weight="900" letter-spacing="2">PLAY FREE AT BEATAI.GAMES</text></g></svg>`;
  res.status(200).setHeader('Content-Type','image/svg+xml; charset=utf-8').setHeader('Cache-Control','public, max-age=300, s-maxage=86400').setHeader('X-Content-Type-Options','nosniff').send(svg);
};
